- app/src/main/java/ch/sbb/polarion/extension/generic/GenericUiServlet.java
- app/src/main/resources/js/common.js
- app/src/main/resources/js/custom-select.js
- app/src/test/java/ch/sbb/polarion/extension/generic/GenericUiServletTest.java
Several fixes for security alerts found by GitHub.
> fix: security alerts fix

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/workflows/maven-release.yml
- .github/workflows/pr.yml
- .github/workflows/release-please.yml
- .pre-commit-config.yaml
- .yamlfix.toml
- CONTRIBUTING.md
- renovate.json
The template was adapted and the changes must be taken over in this repos
> ci: update workflows and configurations with repo template

- app/src/main/resources/css/github-markdown-light.css
- pom/pom.xml
CSS from github added as well, refuse using activeByDefault maven which is broken by design
> feat: maven profile for auto generation of about page based on readme.md added

- app/src/main/resources/js/custom-select.js
> fix: Fixed loading named settings

- .github/workflows/maven-release.yml
- LICENSES/SBB.txt
- app/pom.xml
- pom.xml
- pom/pom.xml
when the artefacts are deployed to Maven Central they can be found easier by Renovate and Maven Build
> 26 renovate failed to look up chsbbpolarionextensionschsbbpolarionextensiongenericparent pom

- app/src/main/java/ch/sbb/polarion/extension/generic/rest/exception/BadRequestExceptionMapper.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/exception/ForbiddenExceptionMapper.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/exception/IllegalArgumentExceptionMapper.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/exception/IllegalStateExceptionMapper.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/exception/InternalServerErrorExceptionMapper.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/exception/NotFoundExceptionMapper.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/exception/ObjectNotFoundExceptionMapper.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/exception/UncaughtExceptionMapper.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/model/ErrorEntity.java
Refs: https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#33
Exception will be returned as JSON objects.
> fix: Changed exception mapping logic.

- pom.xml
> ci: auto release after close configurable

- app/src/main/resources/js/common.js
Refs: https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#33
> fix: Changed logic for exception handling

- README.md
> docs: README.md updated according to the latest changes

- pom.xml
> feat: by default markdown2html-maven-plugin stops building on error

- app/src/main/java/ch/sbb/polarion/extension/generic/auth/AbstractAuthValidator.java
- app/src/main/java/ch/sbb/polarion/extension/generic/auth/AuthValidator.java
- app/src/main/java/ch/sbb/polarion/extension/generic/auth/PersonalAccessTokenValidator.java
- app/src/main/java/ch/sbb/polarion/extension/generic/auth/ValidatorFactory.java
- app/src/main/java/ch/sbb/polarion/extension/generic/auth/ValidatorType.java
- app/src/main/java/ch/sbb/polarion/extension/generic/auth/XsrfTokenValidator.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/filter/AuthenticationFilter.java
- app/src/test/java/ch/sbb/polarion/extension/generic/rest/filter/AuthenticationFilterTest.java
> feat: XSRF Token support

- app/src/main/java/ch/sbb/polarion/extension/generic/auth/XsrfTokenValidator.java
- app/src/test/java/ch/sbb/polarion/extension/generic/rest/filter/AuthenticationFilterTest.java
> fix: check polarion configuration whether XSRF Token is enabled

- README.md
- pom.xml
> feat: swagger-maven-plugin added for OpenAPl spec generation

- app/src/main/resources/js/common.js
Sometimes we need to get some advanced data from XMLHttpRequest. So now we have this object in onOk & onError callbacks. Also there was added the check for so called 'directory traversal' issue.
> chore: slight callAsync improvements

- app/src/main/java/ch/sbb/polarion/extension/generic/fields/converters/StringCSVToListConverter.java
- app/src/main/java/ch/sbb/polarion/extension/generic/fields/converters/StringToEnumOptionConverter.java
- app/src/test/java/ch/sbb/polarion/extension/generic/fields/CustomFieldEnumConverterTest.java
Refs: #104
Trim CSV & enum values.
> fix: cannot insert csv with spaces next to comma into multi-enum field

- app/src/main/resources/js/common.js
> fix: JavaScript error 'getStringIfTextResponse not a function' fixed

- pom.xml
> chore(deps): update dependency ch.sbb.maven.plugins:markdown2html-maven-plugin to v1.2.1

- pom.xml
> feat: jersey-client added as test dependency

- .github/workflows/maven-build.yml
> ci: do not upload asset for generic

- .github/workflows/maven-build.yml
> ci: upload asset for generic

- .github/workflows/maven-build.yml
- pom.xml
> fix: upload tests jar to maven central and github packages

- .github/workflows/maven-build.yml
- README.md
- app/src/main/java/ch/sbb/polarion/extension/generic/util/ScopeUtils.java
- pom.xml
> feat: sonarcloud support added

- app/src/main/java/ch/sbb/polarion/extension/generic/util/ScopeUtils.java
- pom.xml
The Sonar config is still not optimal and must be fixed
> fix: sonar configuration

- app/src/main/java/ch/sbb/polarion/extension/generic/auth/XsrfTokenValidator.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/filter/LogoutFilter.java
- app/src/test/java/ch/sbb/polarion/extension/generic/rest/filter/LogoutFilterTest.java
> fix: use separate attribute for XSRF token in LogoutFilter

- pom.xml
> fix: processing URLs in About page

- .github/workflows/maven-build.yml
comments from GitHub actions workflow are removed
> ci: remove comments from github actions workflow

- app/src/main/java/ch/sbb/polarion/extension/generic/rest/controller/ExtensionInfoInternalController.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/controller/NamedSettingsApiScopeAgnosticController.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/controller/NamedSettingsInternalController.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/model/Context.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/model/ErrorEntity.java
- app/src/main/java/ch/sbb/polarion/extension/generic/rest/model/Version.java
- app/src/main/java/ch/sbb/polarion/extension/generic/settings/Revision.java
- app/src/main/java/ch/sbb/polarion/extension/generic/settings/SettingName.java
- app/src/main/java/ch/sbb/polarion/extension/generic/settings/SettingsModel.java
...improvements
Refs: #154
Added additional Open API annotations
> feat: Extended REST APi annotation

- app/src/main/java/ch/sbb/polarion/extension/generic/settings/SettingsModel.java
- app/src/test/java/ch/sbb/polarion/extension/generic/settings/SettingsModelDeserializationTest.java
> feat: deserialize methods with defaultValue parameter

- README.md
- app/src/main/java/ch/sbb/polarion/extension/generic/properties/ExtensionConfiguration.java
- app/src/main/java/ch/sbb/polarion/extension/generic/util/ContextUtils.java
- pom.xml
It provides the possibility to override the config prefix for non-SBB extensions
Refs: #163
> feat: Configuration-Properties-Prefix added to manifest

- app/src/main/java/ch/sbb/polarion/extension/generic/rest/controller/ExtensionInfoInternalController.java
> chore: Removed API info

- app/src/main/java/ch/sbb/polarion/extension/generic/rest/model/Context.java
- app/src/main/java/ch/sbb/polarion/extension/generic/util/ContextUtils.java
- app/src/main/java/ch/sbb/polarion/extension/generic/util/ManifestUtils.java
- app/src/test/java/ch/sbb/polarion/extension/generic/properties/GetterFinderTest.java
- app/src/test/java/ch/sbb/polarion/extension/generic/rest/model/ContextTest.java
- app/src/test/java/ch/sbb/polarion/extension/generic/settings/GenericNamedSettingsTest.java
- app/src/test/java/ch/sbb/polarion/extension/generic/util/ContextUtilsTest.java
we should not allow providing empty extension context
> feat: extension context should not be null or blank

- app/src/test/java/ch/sbb/polarion/extension/generic/context/CurrentContextConfig.java
- app/src/test/java/ch/sbb/polarion/extension/generic/context/CurrentContextExtension.java
- app/src/test/java/ch/sbb/polarion/extension/generic/properties/GetterFinderTest.java
- app/src/test/java/ch/sbb/polarion/extension/generic/settings/GenericNamedSettingsTest.java
> feat: current context for test classes

- app/src/main/java/ch/sbb/polarion/extension/generic/properties/ExtendedProperties.java
- app/src/main/java/ch/sbb/polarion/extension/generic/properties/ExtensionConfiguration.java
- app/src/main/java/ch/sbb/polarion/extension/generic/properties/GetterFinder.java
- app/src/main/java/ch/sbb/polarion/extension/generic/properties/IExtensionConfiguration.java
- app/src/main/resources/META-INF/resources/common/jsp/about.jsp
- app/src/test/java/ch/sbb/polarion/extension/generic/properties/ExtendedPropertiesTest.java
> feat: "default" and "description" columns added to configuration properties table in About page

- app/src/main/java/ch/sbb/polarion/extension/generic/properties/ExtensionConfiguration.java
> feat: default value for "debug" configuration option

- app/src/main/java/ch/sbb/polarion/extension/generic/properties/ConfigurationProperties.java
- app/src/main/java/ch/sbb/polarion/extension/generic/properties/ExtensionConfiguration.java
- app/src/main/java/ch/sbb/polarion/extension/generic/properties/IExtensionConfiguration.java
- app/src/main/java/ch/sbb/polarion/extension/generic/properties/SystemProperties.java
- app/src/main/resources/META-INF/resources/common/jsp/about.jsp
- app/src/test/java/ch/sbb/polarion/extension/generic/context/CurrentContextConfig.java
- app/src/test/java/ch/sbb/polarion/extension/generic/context/CurrentContextExtension.java
- app/src/test/java/ch/sbb/polarion/extension/generic/context/SystemPropertiesExtension.java
- app/src/test/java/ch/sbb/polarion/extension/generic/properties/ExtensionConfigurationTest.java
> feat: getting configured but obsolete/non-valid options for extension

- pom.xml
Refs: #199
remove unwanted artifacts from about page
> feat: removing sonarcloud badges from about page of extensions

- app/src/main/java/ch/sbb/polarion/extension/generic/settings/SettingsService.java
- pom.xml
> feat: polarion 2410 support

- pom.xml
Refs: 212
will be replaced in diff-tool and in test-data
> feat: javax.transaction-api for test scope

- pom.xml
> chore: remove unused sonar-maven-plugin

- pom.xml
This reverts commit 5dbfa5a66aab61c840857a1ba663a94a8b436064.
> chore: reverted remove unused sonar-maven-plugin

- .mvn/maven.config
- pom.xml
as soon as we are able to migrate
> feat!: polarion2410 support

- README.md
> feat: README.md updated

- app/src/main/java/ch/sbb/polarion/extension/generic/configuration/GenericPolarionStatusProvider.java
- app/src/main/java/ch/sbb/polarion/extension/generic/util/VersionUtils.java
- app/src/main/resources-filtered/generic.properties
- app/src/test/java/ch/sbb/polarion/extension/generic/configuration/GenericPolarionStatusProviderTest.java
- pom.xml
Polarion status provider and maven resource filtering added
> feat: Add Polarion status provider and maven resource filtering 

- .github/workflows/maven-build.yml
- .github/workflows/release-please.yml
there was a problem with the upload to GH releases which had to be fixed ASAP 
> chore: update GitHub Actions workflows for release process

- app/src/test/java/ch/sbb/polarion/extension/generic/test_extensions/PlatformContextMockExtension.java
- app/src/test/java/ch/sbb/polarion/extension/generic/test_extensions/TransactionalExecutorExtension.java
> chore: extend mock context annotations

- app/src/main/java/ch/sbb/polarion/extension/generic/fields/model/Option.java
- app/src/main/java/ch/sbb/polarion/extension/generic/service/PolarionService.java
- app/src/main/java/ch/sbb/polarion/extension/generic/util/EnumUtils.java
Provide icon URLs for enum options
> feat: Provide icon URLs for enum options

- app/src/main/java/ch/sbb/polarion/extension/generic/properties/PropertyMappingScanner.java
- app/src/test/java/ch/sbb/polarion/extension/generic/properties/PropertyMappingScannerTest.java
Refs: #266
some sonarcloud fixes
> chore: sonarcloud fixes

- app/src/test/java/ch/sbb/polarion/extension/generic/test_extensions/TransactionalExecutorExtension.java
> fix: fix transaction mocks for TransactionalExecutor

- app/src/main/java/ch/sbb/polarion/extension/generic/util/ContextUtils.java
- pom.xml
> fix: ContextUtils search only for files skipping bundleresource:// paths
